In [4]:
import pandas as pd
import json
import random

import os
import matplotlib.pyplot as plt
import numpy as np

## Flattenning the JSON Data given in dataset.

In [5]:
columns = ['device', 'geoNetwork', 'totals', 'trafficSource'] # Columns that have json format



#Code to transform the json format columns in table
def json_read(dir_path , nrows=None):
    
    data_frame = dir_path 
    
    #Importing the dataset
    df = pd.read_csv(data_frame, 
                     converters={column: json.loads for column in columns}, # loading the json columns properly
                     dtype={'fullVisitorId': 'str'}, # transforming this column to string
                     nrows = nrows
                     )
    
    for column in columns: 
        #It will normalize and set the json to a table
        column_as_df = pd.json_normalize(df[column]) 
        # here will be set the name using the category and subcategory of json columns
        column_as_df.columns = [f"{column}.{subcolumn}" for subcolumn in column_as_df.columns] 
        # after extracting the values, let drop the original columns
        df = df.drop(column, axis=1).merge(column_as_df, right_index=True, left_index=True)
        
    # Printing the shape of dataframes that was imported     
    print(f"Loaded {os.path.basename(data_frame)}. Shape: {df.shape}")
    return df

In [6]:
# Creating Dataframe using train.csv
df = json_read(r"train.csv",40000)

Loaded train.csv. Shape: (40000, 54)

In [7]:
pd.options.display.max_columns = 60
df.head()

,channelGrouping,date,fullVisitorId,sessionId,socialEngagementType,visitId,visitNumber,visitStartTime,device.browser,device.browserVersion,device.browserSize,device.operatingSystem,device.operatingSystemVersion,device.isMobile,device.mobileDeviceBranding,device.mobileDeviceModel,device.mobileInputSelector,device.mobileDeviceInfo,device.mobileDeviceMarketingName,device.flashVersion,device.language,device.screenColors,device.screenResolution,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.cityId,geoNetwork.networkDomain,geoNetwork.latitude,geoNetwork.longitude,geoNetwork.networkLocation,totals.visits,totals.hits,totals.pageviews,totals.bounces,totals.newVisits,totals.transactionRevenue,trafficSource.campaign,trafficSource.source,trafficSource.medium,trafficSource.keyword,trafficSource.adwordsClickInfo.criteriaParameters,trafficSource.isTrueDirect,trafficSource.referralPath,trafficSource.adwordsClickInfo.page,trafficSource.adwordsClickInfo.slot,trafficSource.adwordsClickInfo.gclId,trafficSource.adwordsClickInfo.adNetworkType,trafficSource.adwordsClickInfo.isVideoAd,trafficSource.adContent
0,Organic Search,20160902,1131660440785968503,1131660440785968503_1472830385,Not Socially Engaged,1472830385,1,1472830385,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Western Asia,Turkey,Izmir,(not set),Izmir,not available in demo dataset,ttnet.com.tr,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Organic Search,20160902,377306020877927890,377306020877927890_1472880147,Not Socially Engaged,1472880147,1,1472880147,Firefox,not available in demo dataset,not available in demo dataset,Macintosh,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Oceania,Australasia,Australia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,dodo.net.au,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Organic Search,20160902,3895546263509774583,3895546263509774583_1472865386,Not Socially Engaged,1472865386,1,1472865386,Chrome,not available in demo dataset,not available in demo dataset,Windows,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Europe,Southern Europe,Spain,Community of Madrid,(not set),Madrid,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,(not provided),not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Organic Search,20160902,4763447161404445595,4763447161404445595_1472881213,Not Socially Engaged,1472881213,1,1472881213,UC Browser,not available in demo dataset,not available in demo dataset,Linux,not available in demo dataset,False,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,desktop,Asia,Southeast Asia,Indonesia,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,1,NaN,(not set),google,organic,google + online,not available in demo dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Organic Search,20160902,27294437909732085,27294437909732085_1472822600,Not Socially Engaged,1472822600,2,1472822600,Chrome,not available in demo dataset,not available in demo dataset,Android,not available in demo dataset,True,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,mobile,Europe,Northern Europe,United Kingdom,not available in demo dataset,not available in demo dataset,not available in demo dataset,not available in demo dataset,unknown.unknown,not available in demo dataset,not available in demo dataset,not available in demo dataset,1,1,1,1,NaN,NaN,(not set),google,organic,(not provided),not available in demo dataset,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#understanding stats of the data
df.describe()

               date       visitId   visitNumber  visitStartTime
count  4.000000e+04  4.000000e+04  40000.000000    4.000000e+04
mean   2.016576e+07  1.485015e+09      2.158750    1.485015e+09
std    4.693465e+03  8.921844e+06      8.446554    8.921844e+06
min    2.016081e+07  1.470896e+09      1.000000    1.470899e+09
25%    2.016111e+07  1.478955e+09      1.000000    1.478955e+09
50%    2.017011e+07  1.484299e+09      1.000000    1.484299e+09
75%    2.017050e+07  1.493679e+09      1.000000    1.493679e+09
max    2.017063e+07  1.498892e+09    389.000000    1.498892e+09

In [9]:
df.shape

(40000, 54)

In [10]:
df.dtypes

channelGrouping                                      object
date                                                  int64
fullVisitorId                                        object
sessionId                                            object
socialEngagementType                                 object
visitId                                               int64
visitNumber                                           int64
visitStartTime                                        int64
device.browser                                       object
device.browserVersion                                object
device.browserSize                                   object
device.operatingSystem                               object
device.operatingSystemVersion                        object
device.isMobile                                        bool
device.mobileDeviceBranding                          object
device.mobileDeviceModel                             object
device.mobileInputSelector                           object
device.mobileDeviceInfo                              object
device.mobileDeviceMarketingName                     object
device.flashVersion                                  object
device.language                                      object
device.screenColors                                  object
device.screenResolution                              object
device.deviceCategory                                object
geoNetwork.continent                                 object
geoNetwork.subContinent                              object
geoNetwork.country                                   object
geoNetwork.region                                    object
geoNetwork.metro                                     object
geoNetwork.city                                      object
geoNetwork.cityId                                    object
geoNetwork.networkDomain                             object
geoNetwork.latitude                                  object
geoNetwork.longitude                                 object
geoNetwork.networkLocation                           object
totals.visits                                        object
totals.hits                                          object
totals.pageviews                                     object
totals.bounces                                       object
totals.newVisits                                     object
totals.transactionRevenue                            object
trafficSource.campaign                               object
trafficSource.source                                 object
trafficSource.medium                                 object
trafficSource.keyword                                object
trafficSource.adwordsClickInfo.criteriaParameters    object
trafficSource.isTrueDirect                           object
trafficSource.referralPath                           object
trafficSource.adwordsClickInfo.page                  object
trafficSource.adwordsClickInfo.slot                  object
trafficSource.adwordsClickInfo.gclId                 object
trafficSource.adwordsClickInfo.adNetworkType         object
trafficSource.adwordsClickInfo.isVideoAd             object
trafficSource.adContent                              object
dtype: object

In [11]:
def Null_Count(df):
    # this operation gives a dataframe of number of null values corresponding to column name.
    df_null = df.isnull().sum().sort_values(ascending = False).rename("Null").reset_index()
    return df_null

In [12]:
df_null = Null_Count(df)

## Finding Null percentage for major columns

In [13]:
n_rows = df.shape[0]
null_percent = (df_null['Null']*100)/n_rows
# print(null_percent)
df_null = pd.concat([df_null['index'] , df_null['Null'], null_percent],axis = 1 , keys=['Column','Null_rows','Null_percent'])
df_null = df_null[df_null['Null_percent']!=0.00]
print(df_null)

                                          Column  Null_rows  Null_percent
0                      totals.transactionRevenue      39515       98.7875
1                        trafficSource.adContent      39459       98.6475
2       trafficSource.adwordsClickInfo.isVideoAd      39042       97.6050
3   trafficSource.adwordsClickInfo.adNetworkType      39042       97.6050
4            trafficSource.adwordsClickInfo.slot      39042       97.6050
5            trafficSource.adwordsClickInfo.page      39042       97.6050
6           trafficSource.adwordsClickInfo.gclId      39007       97.5175
7                     trafficSource.isTrueDirect      28683       71.7075
8                     trafficSource.referralPath      24038       60.0950
9                          trafficSource.keyword      22846       57.1150
10                                totals.bounces      19603       49.0075
11                              totals.newVisits       8557       21.3925
12                              totals.pageviews          3        0.0075

In [14]:
#Changing revenue type from object to float
df['totals.transactionRevenue'] = df['totals.transactionRevenue'].astype(float)

## Checking Revenue generated corresponding to each visitorId

In [15]:
revenue_per_visitor = df.groupby("fullVisitorId")["totals.transactionRevenue"].sum().reset_index()
revenue_per_visitor.shape
revenue_per_visitor.head()

         fullVisitorId  totals.transactionRevenue
0  0000174067426171406                        0.0
1  0000245437374675368                        0.0
2  0000750929315523353                        0.0
3  0001156383977201253                        0.0
4  0001331947010319592                        0.0

In [16]:
df['totals.transactionRevenue'].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: totals.transactionRevenue, dtype: float64

### What do you do about missing data (if any)?
- Adding default value as 0.0 for all nan values in transactionRevenue data variables because the 'No purchase' entries are encoded as NaN values.

In [17]:
# Filling default values for records with null revenue
df['totals.transactionRevenue'].fillna(0.0, inplace=True)

In [18]:
df['totals.transactionRevenue'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: totals.transactionRevenue, dtype: float64

## Checking No. Of Uniques for each data column

In [19]:
df2 = pd.DataFrame()
df2['Name'] = [col for col in df.columns]
df2['Uniques'] = [df[col].nunique() for col in df.columns]

In [20]:
# Sorting on the basis of unique values 
df2.sort_values(by = 'Uniques')

                                                 Name  Uniques
17                            device.mobileDeviceInfo        1
32                                geoNetwork.latitude        1
35                                      totals.visits        1
30                                  geoNetwork.cityId        1
38                                     totals.bounces        1
39                                   totals.newVisits        1
52           trafficSource.adwordsClickInfo.isVideoAd        1
22                            device.screenResolution        1
21                                device.screenColors        1
20                                    device.language        1
19                                device.flashVersion        1
18                   device.mobileDeviceMarketingName        1
33                               geoNetwork.longitude        1
16                         device.mobileInputSelector        1
15                           device.mobileDeviceModel        1
34                         geoNetwork.networkLocation        1
12                      device.operatingSystemVersion        1
51       trafficSource.adwordsClickInfo.adNetworkType        1
10                                 device.browserSize        1
9                               device.browserVersion        1
45  trafficSource.adwordsClickInfo.criteriaParameters        1
14                        device.mobileDeviceBranding        1
46                         trafficSource.isTrueDirect        1
4                                socialEngagementType        1
13                                    device.isMobile        2
49                trafficSource.adwordsClickInfo.slot        2
23                              device.deviceCategory        3
48                trafficSource.adwordsClickInfo.page        4
43                               trafficSource.medium        6
24                               geoNetwork.continent        6
0                                     channelGrouping        7
41                             trafficSource.campaign        8
11                             device.operatingSystem       14
1                                                date       16
25                            geoNetwork.subContinent       22
53                            trafficSource.adContent       25
8                                      device.browser       26
28                                   geoNetwork.metro       35
37                                   totals.pageviews       96
42                               trafficSource.source      114
36                                        totals.hits      126
6                                         visitNumber      141
26                                 geoNetwork.country      166
27                                  geoNetwork.region      168
29                                    geoNetwork.city      213
47                         trafficSource.referralPath      295
44                              trafficSource.keyword      303
40                          totals.transactionRevenue      371
50               trafficSource.adwordsClickInfo.gclId      905
31                           geoNetwork.networkDomain     3788
2                                       fullVisitorId    36663
7                                      visitStartTime    39221
5                                             visitId    39224
3                                           sessionId    40000

## Removing Constant Columns
### which data columns are most applicable? Which data columns can I eliminate, knowing they won’t solve our problem scenario?
- Removing those columns which contains singular unique value. Their presence does not contribute meaningfully to the analytical process and can be considered redundant. By eliminating these columns, the dataset is streamlined, focusing resources on variables that exhibit variability and are more likely to offer insights during the exploratory phase of data analysis.

In [21]:
# Removing Constant Columns
constant_cols = [row.Name for row in df2.itertuples(index=False) if row.Uniques==1]
print(constant_cols)
#dropping constant_columns from training dataframe
df.drop(constant_cols, axis=1, inplace=True)

['socialEngagementType', 'device.browserVersion', 'device.browserSize', 'device.operatingSystemVersion', 'device.mobileDeviceBranding', 'device.mobileDeviceModel', 'device.mobileInputSelector', 'device.mobileDeviceInfo', 'device.mobileDeviceMarketingName', 'device.flashVersion', 'device.language', 'device.screenColors', 'device.screenResolution', 'geoNetwork.cityId', 'geoNetwork.latitude', 'geoNetwork.longitude', 'geoNetwork.networkLocation', 'totals.visits', 'totals.bounces', 'totals.newVisits', 'trafficSource.adwordsClickInfo.criteriaParameters', 'trafficSource.isTrueDirect', 'trafficSource.adwordsClickInfo.adNetworkType', 'trafficSource.adwordsClickInfo.isVideoAd']

In [22]:
df.shape

(40000, 30)

In [23]:
# Calculating mean and max for checking the average values in revenue series
df['totals.transactionRevenue'].unique().mean() , df['totals.transactionRevenue'].unique().max()

(161765040.43126684, 5498000000.0)

- It is worth noting that mean value is so much inflated for each transaction which is not possible in ideal cases so we will normalising these values
by dividing by 10^6.

In [24]:
# Dividing all data points by 10^6.
df['totals.transactionRevenue'] = df['totals.transactionRevenue']//(10**6)

In [25]:
df['totals.transactionRevenue'].unique().mean() , df['totals.transactionRevenue'].unique().max()

(253.14070351758795, 5498.0)

## Checking and calculating outliers 
### Are there data outliers?
- It is found that there are 99 outliers found for the target variable "transactionRevenue" .

In [26]:
def calc_outliers(df_train):
    # mean value , standard deviation is calculated
    mean_val , std_val = np.mean(df_train) , np.std(df_train)

    # this is the cutoff for the acceptable values for our case , it can vary as per use case.
    threshold = std_val * 4

    # defining in what bracket our data points should lie and outside of this all values are considered an outlier
    lower_threshold = mean_val - threshold
    upper_threshold = mean_val + threshold
    lower_outliers = 0
    upper_outliers = 0
    outliers_indices = []
    for idx , point in enumerate(df_train):
        if point < lower_threshold:
            lower_outliers+=1
            outliers_indices.append(idx)
        if point > upper_threshold:
            upper_outliers+=1
            outliers_indices.append(idx)
    print(f"Lower Outliers: {lower_outliers}")
    print(f"Upper Outliers: {upper_outliers}")
    return outliers_indices

In [27]:
print(calc_outliers(df['totals.transactionRevenue']))

Lower Outliers: 0
Upper Outliers: 99
[753, 859, 893, 942, 1008, 1022, 1027, 1056, 2774, 3381, 3391, 3396, 3405, 3412, 3418, 6584, 6730, 6771, 6782, 8229, 10384, 10412, 10445, 10449, 10482, 10484, 10485, 10497, 11248, 11287, 11314, 11345, 11349, 11356, 11388, 11439, 11450, 11471, 11477, 11482, 13684, 14197, 14202, 14293, 14299, 14341, 14346, 14381, 14394, 17232, 17332, 17345, 17347, 17364, 17371, 19569, 21208, 21247, 21249, 21303, 21314, 21332, 21344, 21348, 22381, 22466, 22467, 22499, 22500, 22513, 22514, 22518, 22522, 28520, 30720, 30808, 30815, 30832, 30875, 30877, 32585, 32652, 32697, 32874, 32881, 32888, 32889, 36522, 36535, 36551, 36600, 36623, 36651, 36658, 36681, 36690, 36696, 36700, 36705]